import Head from "next/head";

// Common CSS
import Header from "../../Components/theme_1/Common/Header";
import MenuBar from "../../Components/theme_1/Common/Menubar";
import Delivary from "../../Components/theme_1/Common/Delivary";
import Footer from "../../Components/theme_1/Common/Footer";
import SocialMedia from "../../Components/theme_1/Common/SocialMedia";
import TinyFooter from "../../Components/theme_1/Common/TinyFooter";

import Banner from "../../Components/theme_1/HomePage/Banner";
import Category from "../../Components/theme_1/HomePage/Category";
import MiddleBanner from "../../Components/theme_1/HomePage/MiddleBanner";
import PopularProduct from "../../Components/theme_1/HomePage/PopularProduct";
import AllProduct from "../../Components/theme_1/HomePage/AllProduct";
import { Editor, Frame } from "@craftjs/core";
import { useEffect, useState } from "react";
import { baseUrl } from "../../constant/constant";
import 'grapesjs/dist/css/grapes.min.css'
import Context from "./context";
// import lz from "lzutf8";

// const editor = new grapesjs.init()
const index = () => {
	const [categories, setCategories] = useState([])
	const [editActive, setEditActive] = useState(false)
	// const { actions, query, enabled } = useEditor((state) => ({
	// 	enabled: editActive
	//   }));

	
	async function fetchCategories(headers) {
		const response = await fetch(
			`${baseUrl}/api/v1/customer/categories`, { headers: headers }
		);
		const data = await response.json();
		if (data.success === true) {
			setCategories(data.data)
		}
	}

	useEffect(() => {
		const headers = {
			shop_id: localStorage.getItem('shop_id'),
		}
		fetchCategories(headers).then(r => console.log())
	}, [])
	return (
		<>
			<Head>
				<title>Sales Solution</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='frontend_asset/images/Logo.png' />
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
				<link
					href='https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap'
					rel='stylesheet'
				/>
			</Head>
			<main>
				{/* <button style={{ position: 'fixed', top: 0, right: 0 }} onClick={() => {
                  const json = lz.decompress(lz.decodeBase64(stateToLoad));
                  actions.deserialize(json);
                }}  className="btn btn-success">Save</button> */}
				<button style={{ position: 'fixed', top: 0, right: 0 }} onClick={() => setEditActive(!editActive)} className="btn btn-success">Edit</button>
				<Context.Provider value={editActive}>
					<Header />
				<Editor resolver={{ MenuBar }}>
					<Frame>
						<MenuBar menu1={'Home'} menu2={'Shop'} menu3={'About Us'} menu4={'Contact Us'} fontSize={'15'} />
					</Frame>
				</Editor>
				<Banner></Banner>
				<Editor resolver={{ Category }}>
					<Frame>
						<Category title={'Categori'} categories={categories} fontSize={'16'} />
					</Frame>
				</Editor>
				<MiddleBanner />
				<Editor resolver={{ PopularProduct }}>
					<Frame>
						<PopularProduct title={'Popular Products'} fontSize={'16'} />
					</Frame>
				</Editor>
				<Editor resolver={{ AllProduct }}>
					<Frame>
						<AllProduct title={'All Products'} fontSize={'16'} />
					</Frame>
				</Editor>
				<Delivary></Delivary>
				<Footer></Footer>
				<SocialMedia></SocialMedia>
				<TinyFooter></TinyFooter>				
				</Context.Provider>
			</main>
			<footer></footer>
		</>
	);
};

export default index;

