import Head from 'next/head';
import Menubar from '../../Components/ThemePage/ThemeTwo/Common/Menubar';
import Hero from '../../Components/ThemePage/ThemeTwo/Common/Hero';
import Service from '../../Components/ThemePage/ThemeTwo/Common/Service';
import Footer from '../../Components/ThemePage/ThemeTwo/Common/Footer';
import CategoryImage from '../../Components/ThemePage/ThemeTwo/HomePage/CategoryImage';
import ProductCarousel from '../../Components/ThemePage/ThemeTwo/HomePage/ProductCarousel';
import ProductBanner from '../../Components/ThemePage/ThemeTwo/HomePage/ProductBanner';
import ProductListCarousel from '../../Components/ThemePage/ThemeTwo/HomePage/ProductListCarousel';




export default function Home() {
  return (
    <div className='ThemeTwo'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Menubar></Menubar>
        <Hero></Hero>
        <Service></Service>
        <CategoryImage/>
        <ProductCarousel/>
        <ProductBanner/>
        <ProductListCarousel/>
        <Footer></Footer>

      </main>

    </div>
  )
}
