import Head from 'next/head'
// import Footer from '../Components/theme_1/Common/Footer'
// import Menubar from '../Components/theme_1/Common/Menubar'
// import CategoryImage from '../Components/HomePage/CategoryImage'
// import ProductBanner from '../Components/HomePage/ProductBanner'
// import ProductCarousel from '../Components/HomePage/ProductCarousel'
// import ProductListCarousel from '../Components/HomePage/ProductListCarousel'




export default function Home() {
  return (
    <div className='ThemeTwo'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
{/*         
        <Menubar></Menubar>
        <Hero></Hero>
        <Service></Service>
        <CategoryImage/>
        <ProductCarousel/>
        <ProductBanner/>
        <ProductListCarousel/>
        <Footer></Footer> */}

      </main>

    </div>
  )
}
